services:
  # 后端 API 服务
  - type: web
    name: study-buddy-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://study-buddy.onrender.com"
      - key: NODE_ENV
        value: "production"

  # 前端静态站点
  - type: static
    name: study-buddy
    buildCommand: "echo 'No build required'"
    staticPublishPath: "./frontend"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html