-- Disable RLS for testing
ALTER TABLE public.records DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resource_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_summaries DISABLE ROW LEVEL SECURITY;